export const STUDENT = "STUDENT";
export const TEACHER = "TEACHER";
export const ADMIN = "ADMIN";
export const PARENT = "PARENT";

export const LOGIN_REQ = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQ = "REGISTER_REQ";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const DASHBOARD_REQ = "DASHBOARD_REQ";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";

